[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:8080 run_production:app"
healthcheckPath = "/"
healthcheckTimeout = 900
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 
