[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind=0.0.0.0:$PORT --workers=4 --timeout=600 app:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
PYTHONUNBUFFERED = "1" 